### ISSUE TITLE
QA: Single subtitle setting

### ISSUE THREAD

**Issue by luoxh8** [ouweiya/Dual-Caption-Blog#17]
Hello,

Thanks for the plugin that allows me to get translated subtitles easily.
But I have some questions I want to consult you.
1. How to set to turn off bilingual translation, I only need the translated subtitles, want to turn off the original subtitles.
2. How to set up automatic open actions, I tried some ways, but I need to manually click the subtitle button of youtube then can display it.

Looking forward for your reply, thanks.

**Comment by ouweiya** [comment]
#### single subtitle
![image](https://user-images.githubusercontent.com/28357731/223468218-42ed0397-c3bc-44cd-bcaa-ea8734f53d6a.png)

#### Automatically turn on subtitles by default

**Comment by luoxh8** [comment]
I modified the title to make it easier for other people to search for this question. Thank you for your answer. I have difficulty replying in time. But thank you anyway.
