### ISSUE TITLE
视频字幕 根据语言 选择不同的字体

### ISSUE THREAD

**Issue by k22725** [ouweiya/Dual-Caption-Blog#3]
UD Digi Kyokasho系列字体显示日文很美观 但是显示英文就会把词拉的太长比例也和翻译的字幕极不协调
鄙人把 日文 中文 英文 全都用所有的字体试了多遍 发现

英文 用【Arial】最舒服 在同样宽度下 在清晰不费眼（无衬线字体）的前提下 显示的字母最多

日文 用[【UD Digi Kyokasho】系列字体](https://ja.wikipedia.org/wiki/UD%E3%83%87%E3%82%B8%E3%82%BF%E3%83%AB%E6%95%99%E7%A7%91%E6%9B%B8%E4%BD%93)显示很舒服 护眼 https://www.morisawa.co.jp/topic/upg201802/

简体中文 用【黑体】最好 在同样宽度下高度相较于英文刚刚好 显示的内容更多而且是无衬线字体 不费眼睛

[繁体中文](https://zh.m.wikipedia.org/zh-hans/%E5%9C%8B%E5%AD%97%E6%A8%99%E6%BA%96%E5%AD%97%E9%AB%94)就[不好搞了](https://louis925.wordpress.com/2018/03/29/%E8%AB%8B%E4%B8%8D%E8%A6%81%E7%94%A8%E5%BE%AE%E8%BB%9F%E9%9B%85%E9%BB%91%E9%AB%94%E4%BE%86%E9%A1%AF%E7%A4%BA%E5%8F%B0%E7%81%A3%E5%8D%80%E7%9A%84%E7%B9%81%E9%AB%94%E5%AD%97/)   [MingLiU-ExtB, PMingLiU-ExtB](https://zh.m.wikipedia.org/zh-hans/%E6%96%B0%E7%B4%B0%E6%98%8E%E9%AB%94)的[走之旁(辶部)](https://zh.wikipedia.org/zh-tw/%E8%BE%B5%E9%83%A8)和[Microsoft JhengHei](https://zh.wikipedia.org/zh-tw/%E5%BE%AE%E8%BB%9F%E6%AD%A3%E9%BB%91%E9%AB%94)差别蛮大

如果能自动判断视频的语言（英 日 韩 法 德 西……）然后把用户设的相应字体对上就好了 跪求未来的更新中能实现

**Comment by ouweiya** [comment]
当然
