### ISSUE TITLE
Youtube 部分视频无法显示中文字幕

### ISSUE THREAD

**Issue by Riczzoe** [ouweiya/Dual-Caption-Blog#30]
在观看 Youtube 的部分视频时会无法显示中文字幕，但能够正常显示英文字幕。以下是部分不能正常显示的视频链接:

https://www.youtube.com/watch?v=HcBordv7aWU&list=PL-ymxv0nOtqrGVyPIpJeostmi7zW5JS5l
https://www.youtube.com/watch?v=qe1ltXdKMow&t=11s

不能正常显示的情况如图所示：
![不能正常显示字幕案例](https://i.imgur.com/iISP9vG.png)

我有尝试过开无痕窗口并且允许 YouTube™ dual subtitles 拓展在无痕模式下运行，但打开上述视频仍然无效。也尝试过重新安装拓展, 更换节点, 但是都不奏效。

并且不能显示中文字幕的视频选择下载任何语言的翻译字幕后，字幕文件都为空。
以上述链接中的[第二个链接](https://www.youtube.com/watch?v=qe1ltXdKMow&t=11s)为例，选择下载简体中文字幕，得到的文件为空文件：
![简体中文字幕文件](https://i.imgur.com/pE20sNz.png)

下载翻译为日语的字幕，同样为空：
![日语字幕文件](https://i.imgur.com/pV1rTQd.png)

**Comment by ouweiya** [comment]
是的，YouTube翻译出了问题，如果字幕是自动生成的并会出现翻译错误。（错误的表现行为是返回的翻译内容是一个换行符）

**Comment by Riczzoe** [comment]
> 是的，YouTube翻译出了问题，如果字幕是自动生成的并会出现翻译错误。（错误的表现行为是返回的翻译内容是一个换行符）

好的，感谢你的回复。那只要等待 Youtube 修复这个问题是吗。我今天在发布issue后不久，打开一些无法正常显示翻译字幕的 youtubw 视频左下方都有提示：

The automatic translation service is interrupted, please try again later.
Automatic translation is temporarily out of order and may resume in a few minutes.

**Comment by ouweiya** [comment]
是的，这是我设置的错误提醒，因为这种问题偶尔会发现，一般几小时或者几天。

**Comment by wenchaoliu-93** [comment]
> 在观看 Youtube 的部分视频时会无法显示中文字幕，但能够正常显示英文字幕。以下是部分不能正常显示的视频链接:
> 
> https://www.youtube.com/watch?v=HcBordv7aWU&list=PL-ymxv0nOtqrGVyPIpJeostmi7zW5JS5l https://www.youtube.com/watch?v=qe1ltXdKMow&t=11s
> 
> 不能正常显示的情况如图所示： ![不能正常显示字幕案例](https://camo.githubusercontent.com/4917e58a197ff87f7bcba2fb82f5fd227b95e93362dd384b4193f677394671fd/68747470733a2f2f692e696d6775722e636f6d2f694953503976472e706e67)
> 
> 我有尝试过开无痕窗口并且允许 YouTube™ dual subtitles 拓展在无痕模式下运行，但打开上述视频仍然无效。也尝试过重新安装拓展, 更换节点, 但是都不奏效。
> 
> 并且不能显示中文字幕的视频选择下载任何语言的翻译字幕后，字幕文件都为空。 以上述链接中的[第二个链接](https://www.youtube.com/watch?v=qe1ltXdKMow&t=11s)为例，选择下载简体中文字幕，得到的文件为空文件： ![简体中文字幕文件](https://camo.githubusercontent.com/a86ca471cb6dc2432900356ce7bc5e1f0be568eee9aacc1357205d4c175200cc/68747470733a2f2f692e696d6775722e636f6d2f70453230734e7a2e706e67)
> 
> 下载翻译为日语的字幕，同样为空： ![日语字幕文件](https://camo.githubusercontent.com/3e7282cdd86fde09a927a7a4d1350281a430e3e5f60019469cf79d21f85913cb/68747470733a2f2f692e696d6775722e636f6d2f705631725451642e706e67)

I have tried [this](https://github.com/jdepoix/youtube-transcript-api), and had the same problem. What I am curious about is the percentage of videos that don't work, and why they didn't. Even for the videos on my own YouTube channel, some worked while some didn't.

**Comment by ouweiya** [comment]
现在YouTube修复了错误，插件恢复了正常。
