### ISSUE TITLE
自动生成的英文字幕无法翻译的问题

### ISSUE THREAD

**Issue by gblue0778** [ouweiya/Dual-Caption-Blog#31]
如题，请问大家有出现相同的问题吗，突然自动生成的英文字幕无法翻译，但是不是自动生成的英文字幕可以翻译，之前两种都可以翻译，不确定是不是和其他插件冲突。

**Comment by a90120411** [comment]
是YouTube的服务器问题，等修复吧。

**Comment by ouweiya** [comment]
是的

**Comment by oyal** [comment]
我这两天也是遇到了这个问题，我试着把插件关了又开😂

**Comment by gblue0778** [comment]
今天发现似乎只有自动生成的英文字幕无法翻译，日文韩文频道自动生成的字幕可以翻译。

**Comment by gblue0778** [comment]
> 我这两天也是遇到了这个问题，我试着把插件关了又开😂

有用吗？我把所有插件全部删掉，只装字幕插件但是还是没法解决。

**Comment by oyal** [comment]
> > 我这两天也是遇到了这个问题，我试着把插件关了又开😂
> 
> 有用吗？我把所有插件全部删掉，只装字幕插件但是还是没法解决。

并没有用，哎，我关掉插件，Youtube自动翻译也不行，Youtube的原因

**Comment by oyal** [comment]
我看短视频有的可以翻译，有的不行，YouTube左下角有提示

![image](https://github.com/ouweiya/Dual-Caption-Blog/assets/88022434/162af28d-c948-4da7-9e5b-42bd080ad0d1)

**Comment by ouweiya** [comment]
非常抱歉，这两天翻译出现了问题，因为使用的YouTube翻译源，造成翻译不稳定。

**Comment by NEEO1881** [comment]
It's not the youtube servers, I tested an extension that not that many people use and it works fine with double subtitles in the same video, whereas 'Dula Subtitles' fails, it hasn't been updated in over a year, that might be the reason. 
Here https://chrome.google.com/webstore/detail/dualsub/gnlibmlfpencglodjpgnalbdebfhpmfp

**Comment by a90120411** [comment]
> It's not the youtube servers, I tested an extension that not that many people use and it works fine with double subtitles in the same video, whereas 'Dula Subtitles' fails, it hasn't been updated in over a year, that might be the reason. Here https://chrome.google.com/webstore/detail/dualsub/gnlibmlfpencglodjpgnalbdebfhpmfp

Thank you for your recommendation, I installed this extension, and it does work good. 
Because this plugin uses its own server to translate subtitles, its API domain is: `https://api.dualsub.xyz/service`
You can see this request in DevTools.

**Comment by ouweiya** [comment]
现在YouTube修复了错误，插件恢复了正常。
