### ISSUE TITLE
无法调整 翻译字幕 的字体大小 

### ISSUE THREAD

**Issue by dbthinking** [ouweiya/Dual-Caption-Blog#4]
chrome与插件皆是最新版本
能调整默认字幕的字体大小  但翻译后的字幕字体大小不能调整

**Comment by dbthinking** [comment]
@ouweiya  谢谢解决了 我没注意到两个字幕可以分别设置样式
这么复杂的交互配置  会考虑单独做个可预览的配置选项页吗

**Comment by ouweiya** [comment]
当在调整设置时，字幕会实时预览。

![image](https://user-images.githubusercontent.com/28357731/195766834-8b2fc425-c432-4cbe-a2ad-6a892bfadb4a.png)
