### ISSUE TITLE
自动翻译出现暂时性故障，可能在几分钟后恢复。

### ISSUE THREAD

**Issue by veyyyyyyy** [ouweiya/Dual-Caption-Blog#41]
下载安装插件后一直显示这句话，翻译不了；然后卸载插件之后油管本来的cc字幕都不能开启了，更不能自己翻译，求问怎么解决

**Comment by ouweiya** [comment]
有时候YouTube请求会失败，等一段时间会恢复，可能几天，可能几小时。

**Comment by zhakeboge** [comment]
一直提示
**自动翻译服务中断，请稍后重试。**
自动翻译出现暂时性故障，可能在几分钟后恢复。
很烦人，怎么办

> 下载安装插件后一直显示这句话，翻译不了；然后卸载插件之后油管本来的cc字幕都不能开启了，更不能自己翻译，求问怎么解决

你先切换翻译成英文，再切换翻译成中文，就能显示双语字幕了。但每次都要如此操作

**Comment by zhakeboge** [comment]
> 有时候YouTube请求会失败，等一段时间会恢复，可能几天，可能几小时。

每到第二天凌晨0点开始，就会显示如下：
![0](https://github.com/ouweiya/Dual-Caption-Blog/assets/94672443/fbd774a0-4f6e-4144-bcbe-4ef34322756b)

怎么关闭这个显示？
现在我都是沉浸式翻译的视频翻译配合这个插件使用。但是上面的提示不知道怎么去掉。

**Comment by WA6666** [comment]
应该是和沉浸式翻译插件的字幕翻译功能打架了，二者卸载其中一个就行

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
装了沉浸式翻译扩展的兄弟，去沉浸式翻译扩展的设置里面，把【永久禁用视频字幕功能】 勾上 就可以正常用这个扩展了

**Comment by stupidoge** [comment]
> 装了沉浸式翻译扩展的兄弟，去沉浸式翻译扩展的设置里面，把【永久禁用视频字幕功能】 勾上 就可以正常用这个扩展了

没有装这个插件的仍然报错，是怎么回事呀

**Comment by Ysllllll** [comment]
把cookie清理一下就行了，还不行就退出账号再清理cookie

**Comment by veyyyyyyy** [comment]
> youtube限制了请求次数，请求的时候会用用户的cookie，所以把cookie清理一下就行了，还不行就退出账号再清理cookie

最有用的一集，按你说的改好了 谢谢

**Comment by Jaaayden** [comment]
> youtube限制了请求次数，请求的时候会用用户的cookie，所以把cookie清理一下就行了，还不行就退出账号再清理cookie

有用

**Comment by stupidoge** [comment]
> > youtube限制了请求次数，请求的时候会用用户的cookie，所以把cookie清理一下就行了，还不行就退出账号再清理cookie
> 
> 最有用的一集，按你说的改好了 谢谢

您好，仍然没有用怎么办呢？
