### ISSUE TITLE
字幕样式的 bug？

### ISSUE THREAD

**Issue by smart-z** [ouweiya/Dual-Caption-Blog#42]
大佬您好，您这个样式似乎有问题
我把第二字幕放到第一字幕下面了，您默认是在上面，当然这个可以设置不算问题。
我第二样式设置为英文，放在第一样式中文的下面，您提供了样式设置，这很好，但是，第一字幕的样式默认保留了背景色，不知道是不是您这边设置的还是一系列环境冲突咋的，如图，我的环境是 arc 浏览器。
![image](https://github.com/ouweiya/Dual-Caption-Blog/assets/1166675/82bda407-72a7-4b63-be60-d85e00780c72)

咱能不能把第一字幕的背景色干掉，我设置样式吧，把第二字幕也加个背景色，我尽力美化，也只能搞成这样，也不好看呀，还是显得割裂敢和楞。或者您把第一字幕也可以设置下样式。
![image](https://github.com/ouweiya/Dual-Caption-Blog/assets/1166675/143cdcc5-2bf6-4890-9d39-58ca739da4f2)

我个人观察总结，这样可能比较好，当然这只适用于我的情况，得罪了。上面第一字幕正常显示，下面第二字幕弱化且变小一点，毕竟英文字幕若跟中文一样大不协调。然后两个字幕或者统一描边，或者一起有个统一的背景色。您看呢，谢谢。

**Comment by ouweiya** [comment]
上下字幕应该都可以设置背景颜色，是不是忘记了选择字幕？点击按钮选择对应的字幕设置样式。

![image](https://github.com/ouweiya/Dual-Caption-Blog/assets/28357731/c3563419-9350-4b36-9354-d7c68cda46cd)

**Comment by smart-z** [comment]
> 上下字幕应该都可以设置背景颜色，是不是忘记了选择字幕？点击按钮选择对应的字幕设置样式。
> 
> ![image](https://private-user-images.githubusercontent.com/28357731/293985266-c3563419-9350-4b36-9354-d7c68cda46cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzU2NTcsIm5iZiI6MTcwNDUzNTM1NywicGF0aCI6Ii8yODM1NzczMS8yOTM5ODUyNjYtYzM1NjM0MTktOTM1MC00YjM2LTkzNTQtZDdjNjhjZGE0NmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEwMDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MGMwZGFhMjdlYWJjZjg4MmE2ZjhiYzhkOWYxN2U1YThiODZmYjRiNzU4NWE1MDJiNWE5ZjMwMWY1NTgzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH_DOwbtFKBikRfy_fa6p9FspEqJh54rEJZ9u0cJVWY)


在那个位置做两个功能，既可以切换又可以选择。。。有点少见啊。。。这个选中的样式状态让我觉得似乎是某种 span 的 focus 而不是 button 的 active。您不说我还真没发现，对于普通用户不咋看文档的人。。。
还是谢谢大佬提醒，我改好了。
