### ISSUE TITLE
会上架Firefox浏览器吗？

### ISSUE THREAD

**Issue by lyizhuo** [ouweiya/Dual-Caption-Blog#9]
好像目前只支持Chrome和Edge，希望能上架Friefox，感谢

**Comment by ouweiya** [comment]
会的。

**Comment by spphinslove** [comment]
> 会的。

然后鸽了

**Comment by ouweiya** [comment]
不好意思，确实拖延了太久，但是，目前已经开始进行Firefox兼容工作，预计很快就能使用上，Firefox商店已经有同名扩展，但是那是假冒程序，请勿使用。

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
> 不好意思，确实拖延了太久，但是，目前已经开始进行Firefox兼容工作，预计很快就能使用上，Firefox商店已经有同名扩展，但是那是假冒程序，请勿使用。

没绷住，李鬼都出来了，李逵还不知道在哪
